### ISSUE TITLE
REST GET /character

### ISSUE THREAD

**Issue by LokiMidgard** [LokiMidgard/dreibart-fernkampf-tool#1]
Für die liste aller Charactere, sollten denke ich folgende Daten übermittelt werden:
```json
[
    {
        "id": 3,
        "name": "Max musterman",
        "world": "Cornea", // ← Ist das immer eine? Andernfalls sollte dies ein Arry von Strings sein
        "type": "Landadel", // ← Immer String, auch wenn im feld eine Zahl steht…
        // eventuell noch folgednde
        "attribute-points": {
            "max": 30,
            "available": 4,
        },
        "skill-points": {
            "max": 30,
            "available": 4,
        },
    },
    {
        // Weitere …
    }
]
```
Ich gehe davon aus das die Anzahl der Charactere nicht allzu groß wird, daher denke ich können wir auf querys wie `from`, `count` und `filter` verzichten und eventuelles Paging und filtern Clientseitig machen.

**Comment by LokiMidgard** [comment]
Kein image statdessen gibt des das image über den Server mittels character id

**Comment by goebelt** [comment]
worldId wird jetzt übermittelt.
ansonsten ist das Feature umgesetzt und abgeschlossen.

**Comment by goebelt** [comment]
abgeschlossen und getestet

**Comment by LokiMidgard** [comment]
Sollte WorldId nich eine Zahl sein?

**Comment by goebelt** [comment]
id als Zahl umgesetzt, kann geschlossen werden
