### ISSUE TITLE
worldId in Charakter-Auswahl zum Gruppieren verwenden

### ISSUE THREAD

**Issue by goebelt** [LokiMidgard/dreibart-fernkampf-tool#11]
Datenstruktur enthält ein zusätzliches Feld "worldId", welches den eindeutigen Schlüssel zur Spielwelt enthält
Nutzbar für Gruppierung, Filterung und Suche

**Comment by LokiMidgard** [comment]
Wird nun zum Grupiren verwendet. Allerdings erwachte ich eine Zahl. sobald #1 gefixde is, sollte es gehen
