### ISSUE TITLE
Suchfunktion für Charakterliste

### ISSUE THREAD

**Issue by goebelt** [LokiMidgard/dreibart-fernkampf-tool#13]
mittels Volltestsuche soll die Charakterliste nach Schlagworten durchsucht werden können
- Name
- Welt
- eventuell zukünftiges Feld "Charakterbeschreibung"

**Comment by LokiMidgard** [comment]
Mann kann aktuell nach Name und Typ Suchen.

Welt ginge auch oder soll das über einen Filter gemacht werden? Gerade kurze Strings könnten unbeabsichtigt welten Matchen und dann jeden Character der Welt anzeigen…

**Comment by LokiMidgard** [comment]
Aktuell kann man Welten über Checkboxen filtern

**Comment by goebelt** [comment]
Passt so aus meiner Sicht
