### ISSUE TITLE
Suchfunktion in Notizen

### ISSUE THREAD

**Issue by goebelt** [LokiMidgard/dreibart-fernkampf-tool#15]
Notizen sollen durchsuchbar sein
Schlagwortsuche in 
- Titel
- Text

Unter Verwendung von Platzhaltern soll es auch möglich sein Teilworte oder kombinierte Suchbegriffe zu verwenden

**Comment by LokiMidgard** [comment]
Was für Platzhalter schweben dir vor?
Aktuell sucht er nach jedem eingegebenen Wort, bzw teile davon

`Ha Wo` Matched in dem Text *Dies ist ein **Ha**llo **Wo**rld eintrag* Damit ein Eintrag gematched wird müssen alle teile in dem Eintrag vorkommen

Ich könnte mir die Modifire ganze wörter vortsellen, dann müssen alle wörter exakt matchen `Ha` würde dann nicht mehr `Hallo` matchen, sondern nur noch ` Ha `

Oder Zusammenhägender text, dann würden spaces wie noraler Text behandelt werden, `Hallo World` würde dann nicht mehr `Hallo` und `World` matchen, sondern nur noch beide direkt hintereinander.

Theoretich sollten ach Regex ausdrücke möglich sein

**Comment by goebelt** [comment]
Suche wie getestet erst mal ausreichend.
