### ISSUE TITLE
Notizen benötigen einen Typen

### ISSUE THREAD

**Issue by LokiMidgard** [LokiMidgard/dreibart-fernkampf-tool#16]
Notizen sollen filterbar sein, je nachdem ob es vereinbarugen sind oder nicht.

Dafür benötige ich ein Feld ob es eine Vereinbarung ist.

Zudem haben solche vereinbarungen zusätzliche Metadaten? Wenn Ja, rechtfertigt es eine Eigen view Vereinbarungen unabhänig von Notizen? Sollte es auch eine Unabhänigen REST call geben?

Blockiert #14

**Comment by goebelt** [comment]
Vereinbarungsinformationen werden geliefert. Issue damit geschlossen.
