### ISSUE TITLE
Erlaube CORS von allen devtunnels

### ISSUE THREAD

**Issue by LokiMidgard** [LokiMidgard/dreibart-fernkampf-tool#17]
Zum debuggen wird ja ein portforwarding von euw.devtunnels.ms verwendet. Über längere Zeit ist der Präfix nicht stabil und wechseln ab und an, daher sollten für debugging zwecke alle varianten von https://xxxxxxxxxx.euw.devtunnels.ms/ für CORS erlaubt sein.

**Comment by goebelt** [comment]
erledigt. alle Anfragen von ".euw,devtunnels.ms" sollten ok sein
